version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
    groups:
      bun-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "swift-actions/setup-swift"
        update-types:
          - "version-update:semver-major"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
