[pre-commit]
parallel = true

[pre-commit.commands.format]
glob = "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
run = "bunx biome format --write --files-ignore-unknown=true {staged_files}"

[pre-commit.commands.biome]
glob = "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
run = "bunx biome check --fix --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}"
