//
// SiteStandardTheme.generated.swift is automatically generated by lexicodegen.
// Do not edit this file directly.
// Update the generator inputs or generator code, then regenerate.
//

import Foundation


public struct SiteStandardThemeBasic: Codable, Sendable, Equatable {
	public static let typeIdentifier = "site.standard.theme.basic"

	public let accent: SiteStandardThemeBasicAccent
	public let accentForeground: SiteStandardThemeBasicAccent
	public let background: SiteStandardThemeBasicAccent
	public let foreground: SiteStandardThemeBasicAccent

	public init(
		accent: SiteStandardThemeBasicAccent,
		accentForeground: SiteStandardThemeBasicAccent,
		background: SiteStandardThemeBasicAccent,
		foreground: SiteStandardThemeBasicAccent
	) {
		self.accent = accent
		self.accentForeground = accentForeground
		self.background = background
		self.foreground = foreground
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		_ = try container.decodeIfPresent(String.self, forKey: .typeIdentifier)
		accent = try container.decode(SiteStandardThemeBasicAccent.self, forKey: .accent)
		accentForeground = try container.decode(SiteStandardThemeBasicAccent.self, forKey: .accentForeground)
		background = try container.decode(SiteStandardThemeBasicAccent.self, forKey: .background)
		foreground = try container.decode(SiteStandardThemeBasicAccent.self, forKey: .foreground)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(Self.typeIdentifier, forKey: .typeIdentifier)
		try container.encode(accent, forKey: .accent)
		try container.encode(accentForeground, forKey: .accentForeground)
		try container.encode(background, forKey: .background)
		try container.encode(foreground, forKey: .foreground)
	}

	private enum CodingKeys: String, CodingKey {
		case typeIdentifier = "$type"
		case accent = "accent"
		case accentForeground = "accentForeground"
		case background = "background"
		case foreground = "foreground"
	}
}


public indirect enum SiteStandardThemeBasicAccent: Codable, Sendable, Equatable {
	case rgb(SiteStandardThemeColorRgb)
	case unexpected(ATProtocolValueContainer)

	public init(from decoder: Decoder) throws {
		let typeIdentifier = try ATProtocolDecoder.decodeTypeIdentifier(from: decoder)
		switch typeIdentifier {
		case "site.standard.theme.color#rgb": self = .rgb(try SiteStandardThemeColorRgb(from: decoder))
		default: self = .unexpected(try ATProtocolValueContainer(from: decoder))
		}
	}

	public func encode(to encoder: Encoder) throws {
		switch self {
		case .rgb(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "site.standard.theme.color#rgb", to: encoder)
		case .unexpected(let value): try value.encode(to: encoder)
		}
	}
}


public struct SiteStandardThemeColorRgb: Codable, Sendable, Equatable {
	public let b: Int
	public let g: Int
	public let r: Int

	public init(
		b: Int,
		g: Int,
		r: Int
	) {
		self.b = b
		self.g = g
		self.r = r
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		b = try container.decode(Int.self, forKey: .b)
		g = try container.decode(Int.self, forKey: .g)
		r = try container.decode(Int.self, forKey: .r)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(b, forKey: .b)
		try container.encode(g, forKey: .g)
		try container.encode(r, forKey: .r)
	}

	private enum CodingKeys: String, CodingKey {
		case b = "b"
		case g = "g"
		case r = "r"
	}
}


public struct SiteStandardThemeColorRgba: Codable, Sendable, Equatable {
	public let a: Int
	public let b: Int
	public let g: Int
	public let r: Int

	public init(
		a: Int,
		b: Int,
		g: Int,
		r: Int
	) {
		self.a = a
		self.b = b
		self.g = g
		self.r = r
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		a = try container.decode(Int.self, forKey: .a)
		b = try container.decode(Int.self, forKey: .b)
		g = try container.decode(Int.self, forKey: .g)
		r = try container.decode(Int.self, forKey: .r)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(a, forKey: .a)
		try container.encode(b, forKey: .b)
		try container.encode(g, forKey: .g)
		try container.encode(r, forKey: .r)
	}

	private enum CodingKeys: String, CodingKey {
		case a = "a"
		case b = "b"
		case g = "g"
		case r = "r"
	}
}


