//
// ToolsOzoneReport.generated.swift is automatically generated by lexicodegen.
// Do not edit this file directly.
// Update the generator inputs or generator code, then regenerate.
//

import Foundation


public enum ToolsOzoneReportAssignModeratorError: String, Swift.Error, CaseIterable, Sendable {
	case alreadyAssigned = "AlreadyAssigned"
	case invalidAssignment = "InvalidAssignment"

	public init?(transportError: XRPCTransportError) {
		guard let rawValue = transportError.payload?.error else {
			return nil
		}
		self.init(rawValue: rawValue)
	}
}


public struct ToolsOzoneReportAssignModeratorInput: Codable, Sendable, Equatable {
	public let did: DID?
	public let isPermanent: Bool?
	public let queueId: Int?
	public let reportId: Int

	public init(
		did: DID? = nil,
		isPermanent: Bool? = nil,
		queueId: Int? = nil,
		reportId: Int
	) {
		self.did = did
		self.isPermanent = isPermanent
		self.queueId = queueId
		self.reportId = reportId
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		did = try container.decodeIfPresent(DID.self, forKey: .did)
		isPermanent = try container.decodeIfPresent(Bool.self, forKey: .isPermanent)
		queueId = try container.decodeIfPresent(Int.self, forKey: .queueId)
		reportId = try container.decode(Int.self, forKey: .reportId)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(did, forKey: .did)
		try container.encodeIfPresent(isPermanent, forKey: .isPermanent)
		try container.encodeIfPresent(queueId, forKey: .queueId)
		try container.encode(reportId, forKey: .reportId)
	}

	private enum CodingKeys: String, CodingKey {
		case did = "did"
		case isPermanent = "isPermanent"
		case queueId = "queueId"
		case reportId = "reportId"
	}
}


public typealias ToolsOzoneReportAssignModeratorOutput = ToolsOzoneReportDefsAssignmentView


public enum ToolsOzoneReportCreateActivityError: String, Swift.Error, CaseIterable, Sendable {
	case alreadyInTargetState = "AlreadyInTargetState"
	case invalidStateTransition = "InvalidStateTransition"
	case reportNotFound = "ReportNotFound"

	public init?(transportError: XRPCTransportError) {
		guard let rawValue = transportError.payload?.error else {
			return nil
		}
		self.init(rawValue: rawValue)
	}
}


public struct ToolsOzoneReportCreateActivityInput: Codable, Sendable, Equatable {
	public let activity: ToolsOzoneReportDefsReportActivityViewActivity
	public let internalNote: String?
	public let isAutomated: Bool?
	public let publicNote: String?
	public let reportId: Int

	public init(
		activity: ToolsOzoneReportDefsReportActivityViewActivity,
		internalNote: String? = nil,
		isAutomated: Bool? = nil,
		publicNote: String? = nil,
		reportId: Int
	) {
		self.activity = activity
		self.internalNote = internalNote
		self.isAutomated = isAutomated
		self.publicNote = publicNote
		self.reportId = reportId
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		activity = try container.decode(ToolsOzoneReportDefsReportActivityViewActivity.self, forKey: .activity)
		internalNote = try container.decodeIfPresent(String.self, forKey: .internalNote)
		isAutomated = try container.decodeIfPresent(Bool.self, forKey: .isAutomated)
		publicNote = try container.decodeIfPresent(String.self, forKey: .publicNote)
		reportId = try container.decode(Int.self, forKey: .reportId)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(activity, forKey: .activity)
		try container.encodeIfPresent(internalNote, forKey: .internalNote)
		try container.encodeIfPresent(isAutomated, forKey: .isAutomated)
		try container.encodeIfPresent(publicNote, forKey: .publicNote)
		try container.encode(reportId, forKey: .reportId)
	}

	private enum CodingKeys: String, CodingKey {
		case activity = "activity"
		case internalNote = "internalNote"
		case isAutomated = "isAutomated"
		case publicNote = "publicNote"
		case reportId = "reportId"
	}
}


public struct ToolsOzoneReportCreateActivityOutput: Codable, Sendable, Equatable {
	public let activity: ToolsOzoneReportDefsReportActivityView

	public init(
		activity: ToolsOzoneReportDefsReportActivityView
	) {
		self.activity = activity
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		activity = try container.decode(ToolsOzoneReportDefsReportActivityView.self, forKey: .activity)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(activity, forKey: .activity)
	}

	private enum CodingKeys: String, CodingKey {
		case activity = "activity"
	}
}


public struct ToolsOzoneReportDefsAssignmentActivity: Codable, Sendable, Equatable {
	public let previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus?

	public init(
		previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus? = nil
	) {
		self.previousStatus = previousStatus
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		previousStatus = try container.decodeIfPresent(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .previousStatus)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(previousStatus, forKey: .previousStatus)
	}

	private enum CodingKeys: String, CodingKey {
		case previousStatus = "previousStatus"
	}
}


public enum ToolsOzoneReportDefsAssignmentActivityPreviousStatus: String, Codable, CaseIterable, QueryParameterValue, Sendable {
	case open = "open"
	case closed = "closed"
	case escalated = "escalated"
	case queued = "queued"
	case assigned = "assigned"
}


public struct ToolsOzoneReportDefsAssignmentView: Codable, Sendable, Equatable {
	public let did: DID
	public let endAt: ATProtocolDate?
	public let id: Int
	public let moderator: ToolsOzoneTeamDefsMember?
	public let queue: ToolsOzoneQueueDefsQueueView?
	public let reportId: Int
	public let startAt: ATProtocolDate

	public init(
		did: DID,
		endAt: ATProtocolDate? = nil,
		id: Int,
		moderator: ToolsOzoneTeamDefsMember? = nil,
		queue: ToolsOzoneQueueDefsQueueView? = nil,
		reportId: Int,
		startAt: ATProtocolDate
	) {
		self.did = did
		self.endAt = endAt
		self.id = id
		self.moderator = moderator
		self.queue = queue
		self.reportId = reportId
		self.startAt = startAt
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		did = try container.decode(DID.self, forKey: .did)
		endAt = try container.decodeIfPresent(ATProtocolDate.self, forKey: .endAt)
		id = try container.decode(Int.self, forKey: .id)
		moderator = try container.decodeIfPresent(ToolsOzoneTeamDefsMember.self, forKey: .moderator)
		queue = try container.decodeIfPresent(ToolsOzoneQueueDefsQueueView.self, forKey: .queue)
		reportId = try container.decode(Int.self, forKey: .reportId)
		startAt = try container.decode(ATProtocolDate.self, forKey: .startAt)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(did, forKey: .did)
		try container.encodeIfPresent(endAt, forKey: .endAt)
		try container.encode(id, forKey: .id)
		try container.encodeIfPresent(moderator, forKey: .moderator)
		try container.encodeIfPresent(queue, forKey: .queue)
		try container.encode(reportId, forKey: .reportId)
		try container.encode(startAt, forKey: .startAt)
	}

	private enum CodingKeys: String, CodingKey {
		case did = "did"
		case endAt = "endAt"
		case id = "id"
		case moderator = "moderator"
		case queue = "queue"
		case reportId = "reportId"
		case startAt = "startAt"
	}
}


public struct ToolsOzoneReportDefsCloseActivity: Codable, Sendable, Equatable {
	public let previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus?

	public init(
		previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus? = nil
	) {
		self.previousStatus = previousStatus
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		previousStatus = try container.decodeIfPresent(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .previousStatus)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(previousStatus, forKey: .previousStatus)
	}

	private enum CodingKeys: String, CodingKey {
		case previousStatus = "previousStatus"
	}
}


public struct ToolsOzoneReportDefsEscalationActivity: Codable, Sendable, Equatable {
	public let previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus?

	public init(
		previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus? = nil
	) {
		self.previousStatus = previousStatus
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		previousStatus = try container.decodeIfPresent(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .previousStatus)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(previousStatus, forKey: .previousStatus)
	}

	private enum CodingKeys: String, CodingKey {
		case previousStatus = "previousStatus"
	}
}


public struct ToolsOzoneReportDefsHistoricalStats: Codable, Sendable, Equatable {
	public let actionRate: Int?
	public let actionedCount: Int?
	public let avgHandlingTimeSec: Int?
	public let computedAt: ATProtocolDate?
	public let date: String
	public let escalatedCount: Int?
	public let inboundCount: Int?
	public let pendingCount: Int?

	public init(
		actionRate: Int? = nil,
		actionedCount: Int? = nil,
		avgHandlingTimeSec: Int? = nil,
		computedAt: ATProtocolDate? = nil,
		date: String,
		escalatedCount: Int? = nil,
		inboundCount: Int? = nil,
		pendingCount: Int? = nil
	) {
		self.actionRate = actionRate
		self.actionedCount = actionedCount
		self.avgHandlingTimeSec = avgHandlingTimeSec
		self.computedAt = computedAt
		self.date = date
		self.escalatedCount = escalatedCount
		self.inboundCount = inboundCount
		self.pendingCount = pendingCount
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		actionRate = try container.decodeIfPresent(Int.self, forKey: .actionRate)
		actionedCount = try container.decodeIfPresent(Int.self, forKey: .actionedCount)
		avgHandlingTimeSec = try container.decodeIfPresent(Int.self, forKey: .avgHandlingTimeSec)
		computedAt = try container.decodeIfPresent(ATProtocolDate.self, forKey: .computedAt)
		date = try container.decode(String.self, forKey: .date)
		escalatedCount = try container.decodeIfPresent(Int.self, forKey: .escalatedCount)
		inboundCount = try container.decodeIfPresent(Int.self, forKey: .inboundCount)
		pendingCount = try container.decodeIfPresent(Int.self, forKey: .pendingCount)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(actionRate, forKey: .actionRate)
		try container.encodeIfPresent(actionedCount, forKey: .actionedCount)
		try container.encodeIfPresent(avgHandlingTimeSec, forKey: .avgHandlingTimeSec)
		try container.encodeIfPresent(computedAt, forKey: .computedAt)
		try container.encode(date, forKey: .date)
		try container.encodeIfPresent(escalatedCount, forKey: .escalatedCount)
		try container.encodeIfPresent(inboundCount, forKey: .inboundCount)
		try container.encodeIfPresent(pendingCount, forKey: .pendingCount)
	}

	private enum CodingKeys: String, CodingKey {
		case actionRate = "actionRate"
		case actionedCount = "actionedCount"
		case avgHandlingTimeSec = "avgHandlingTimeSec"
		case computedAt = "computedAt"
		case date = "date"
		case escalatedCount = "escalatedCount"
		case inboundCount = "inboundCount"
		case pendingCount = "pendingCount"
	}
}


public struct ToolsOzoneReportDefsLiveStats: Codable, Sendable, Equatable {
	public let actionRate: Int?
	public let actionedCount: Int?
	public let avgHandlingTimeSec: Int?
	public let escalatedCount: Int?
	public let inboundCount: Int?
	public let lastUpdated: ATProtocolDate?
	public let pendingCount: Int?

	public init(
		actionRate: Int? = nil,
		actionedCount: Int? = nil,
		avgHandlingTimeSec: Int? = nil,
		escalatedCount: Int? = nil,
		inboundCount: Int? = nil,
		lastUpdated: ATProtocolDate? = nil,
		pendingCount: Int? = nil
	) {
		self.actionRate = actionRate
		self.actionedCount = actionedCount
		self.avgHandlingTimeSec = avgHandlingTimeSec
		self.escalatedCount = escalatedCount
		self.inboundCount = inboundCount
		self.lastUpdated = lastUpdated
		self.pendingCount = pendingCount
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		actionRate = try container.decodeIfPresent(Int.self, forKey: .actionRate)
		actionedCount = try container.decodeIfPresent(Int.self, forKey: .actionedCount)
		avgHandlingTimeSec = try container.decodeIfPresent(Int.self, forKey: .avgHandlingTimeSec)
		escalatedCount = try container.decodeIfPresent(Int.self, forKey: .escalatedCount)
		inboundCount = try container.decodeIfPresent(Int.self, forKey: .inboundCount)
		lastUpdated = try container.decodeIfPresent(ATProtocolDate.self, forKey: .lastUpdated)
		pendingCount = try container.decodeIfPresent(Int.self, forKey: .pendingCount)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(actionRate, forKey: .actionRate)
		try container.encodeIfPresent(actionedCount, forKey: .actionedCount)
		try container.encodeIfPresent(avgHandlingTimeSec, forKey: .avgHandlingTimeSec)
		try container.encodeIfPresent(escalatedCount, forKey: .escalatedCount)
		try container.encodeIfPresent(inboundCount, forKey: .inboundCount)
		try container.encodeIfPresent(lastUpdated, forKey: .lastUpdated)
		try container.encodeIfPresent(pendingCount, forKey: .pendingCount)
	}

	private enum CodingKeys: String, CodingKey {
		case actionRate = "actionRate"
		case actionedCount = "actionedCount"
		case avgHandlingTimeSec = "avgHandlingTimeSec"
		case escalatedCount = "escalatedCount"
		case inboundCount = "inboundCount"
		case lastUpdated = "lastUpdated"
		case pendingCount = "pendingCount"
	}
}


public struct ToolsOzoneReportDefsNoteActivity: Codable, Sendable, Equatable {

	public init() {}

	public init(from decoder: Decoder) throws {
		_ = try decoder.container(keyedBy: CodingKeys.self)
	}

	public func encode(to encoder: Encoder) throws {
		_ = encoder.container(keyedBy: CodingKeys.self)
	}

	private struct CodingKeys: CodingKey {
		let stringValue = ""
		init?(stringValue: String) {
			return nil
		}

		let intValue: Int? = nil
		init?(intValue: Int) {
			return nil
		}
	}
}


public struct ToolsOzoneReportDefsQueueActivity: Codable, Sendable, Equatable {
	public let previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus?

	public init(
		previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus? = nil
	) {
		self.previousStatus = previousStatus
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		previousStatus = try container.decodeIfPresent(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .previousStatus)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(previousStatus, forKey: .previousStatus)
	}

	private enum CodingKeys: String, CodingKey {
		case previousStatus = "previousStatus"
	}
}


public typealias ToolsOzoneReportDefsReasonAppeal = String


public typealias ToolsOzoneReportDefsReasonChildSafetyCSAM = String


public typealias ToolsOzoneReportDefsReasonChildSafetyGroom = String


public typealias ToolsOzoneReportDefsReasonChildSafetyHarassment = String


public typealias ToolsOzoneReportDefsReasonChildSafetyOther = String


public typealias ToolsOzoneReportDefsReasonChildSafetyPrivacy = String


public typealias ToolsOzoneReportDefsReasonHarassmentDoxxing = String


public typealias ToolsOzoneReportDefsReasonHarassmentHateSpeech = String


public typealias ToolsOzoneReportDefsReasonHarassmentOther = String


public typealias ToolsOzoneReportDefsReasonHarassmentTargeted = String


public typealias ToolsOzoneReportDefsReasonHarassmentTroll = String


public typealias ToolsOzoneReportDefsReasonMisleadingBot = String


public typealias ToolsOzoneReportDefsReasonMisleadingElections = String


public typealias ToolsOzoneReportDefsReasonMisleadingImpersonation = String


public typealias ToolsOzoneReportDefsReasonMisleadingOther = String


public typealias ToolsOzoneReportDefsReasonMisleadingScam = String


public typealias ToolsOzoneReportDefsReasonMisleadingSpam = String


public typealias ToolsOzoneReportDefsReasonOther = String


public typealias ToolsOzoneReportDefsReasonRuleBanEvasion = String


public typealias ToolsOzoneReportDefsReasonRuleOther = String


public typealias ToolsOzoneReportDefsReasonRuleProhibitedSales = String


public typealias ToolsOzoneReportDefsReasonRuleSiteSecurity = String


public typealias ToolsOzoneReportDefsReasonSelfHarmContent = String


public typealias ToolsOzoneReportDefsReasonSelfHarmED = String


public typealias ToolsOzoneReportDefsReasonSelfHarmOther = String


public typealias ToolsOzoneReportDefsReasonSelfHarmStunts = String


public typealias ToolsOzoneReportDefsReasonSelfHarmSubstances = String


public typealias ToolsOzoneReportDefsReasonSexualAbuseContent = String


public typealias ToolsOzoneReportDefsReasonSexualAnimal = String


public typealias ToolsOzoneReportDefsReasonSexualDeepfake = String


public typealias ToolsOzoneReportDefsReasonSexualNCII = String


public typealias ToolsOzoneReportDefsReasonSexualOther = String


public typealias ToolsOzoneReportDefsReasonSexualUnlabeled = String


public enum ToolsOzoneReportDefsReasonType: String, Codable, CaseIterable, QueryParameterValue, Sendable {
	case toolsOzoneReportDefsReasonAppeal = "tools.ozone.report.defs#reasonAppeal"
	case toolsOzoneReportDefsReasonOther = "tools.ozone.report.defs#reasonOther"
	case toolsOzoneReportDefsReasonViolenceAnimal = "tools.ozone.report.defs#reasonViolenceAnimal"
	case toolsOzoneReportDefsReasonViolenceThreats = "tools.ozone.report.defs#reasonViolenceThreats"
	case toolsOzoneReportDefsReasonViolenceGraphicContent = "tools.ozone.report.defs#reasonViolenceGraphicContent"
	case toolsOzoneReportDefsReasonViolenceGlorification = "tools.ozone.report.defs#reasonViolenceGlorification"
	case toolsOzoneReportDefsReasonViolenceExtremistContent = "tools.ozone.report.defs#reasonViolenceExtremistContent"
	case toolsOzoneReportDefsReasonViolenceTrafficking = "tools.ozone.report.defs#reasonViolenceTrafficking"
	case toolsOzoneReportDefsReasonViolenceOther = "tools.ozone.report.defs#reasonViolenceOther"
	case toolsOzoneReportDefsReasonSexualAbuseContent = "tools.ozone.report.defs#reasonSexualAbuseContent"
	case toolsOzoneReportDefsReasonSexualNcii = "tools.ozone.report.defs#reasonSexualNCII"
	case toolsOzoneReportDefsReasonSexualDeepfake = "tools.ozone.report.defs#reasonSexualDeepfake"
	case toolsOzoneReportDefsReasonSexualAnimal = "tools.ozone.report.defs#reasonSexualAnimal"
	case toolsOzoneReportDefsReasonSexualUnlabeled = "tools.ozone.report.defs#reasonSexualUnlabeled"
	case toolsOzoneReportDefsReasonSexualOther = "tools.ozone.report.defs#reasonSexualOther"
	case toolsOzoneReportDefsReasonChildSafetyCsam = "tools.ozone.report.defs#reasonChildSafetyCSAM"
	case toolsOzoneReportDefsReasonChildSafetyGroom = "tools.ozone.report.defs#reasonChildSafetyGroom"
	case toolsOzoneReportDefsReasonChildSafetyPrivacy = "tools.ozone.report.defs#reasonChildSafetyPrivacy"
	case toolsOzoneReportDefsReasonChildSafetyHarassment = "tools.ozone.report.defs#reasonChildSafetyHarassment"
	case toolsOzoneReportDefsReasonChildSafetyOther = "tools.ozone.report.defs#reasonChildSafetyOther"
	case toolsOzoneReportDefsReasonHarassmentTroll = "tools.ozone.report.defs#reasonHarassmentTroll"
	case toolsOzoneReportDefsReasonHarassmentTargeted = "tools.ozone.report.defs#reasonHarassmentTargeted"
	case toolsOzoneReportDefsReasonHarassmentHateSpeech = "tools.ozone.report.defs#reasonHarassmentHateSpeech"
	case toolsOzoneReportDefsReasonHarassmentDoxxing = "tools.ozone.report.defs#reasonHarassmentDoxxing"
	case toolsOzoneReportDefsReasonHarassmentOther = "tools.ozone.report.defs#reasonHarassmentOther"
	case toolsOzoneReportDefsReasonMisleadingBot = "tools.ozone.report.defs#reasonMisleadingBot"
	case toolsOzoneReportDefsReasonMisleadingImpersonation = "tools.ozone.report.defs#reasonMisleadingImpersonation"
	case toolsOzoneReportDefsReasonMisleadingSpam = "tools.ozone.report.defs#reasonMisleadingSpam"
	case toolsOzoneReportDefsReasonMisleadingScam = "tools.ozone.report.defs#reasonMisleadingScam"
	case toolsOzoneReportDefsReasonMisleadingElections = "tools.ozone.report.defs#reasonMisleadingElections"
	case toolsOzoneReportDefsReasonMisleadingOther = "tools.ozone.report.defs#reasonMisleadingOther"
	case toolsOzoneReportDefsReasonRuleSiteSecurity = "tools.ozone.report.defs#reasonRuleSiteSecurity"
	case toolsOzoneReportDefsReasonRuleProhibitedSales = "tools.ozone.report.defs#reasonRuleProhibitedSales"
	case toolsOzoneReportDefsReasonRuleBanEvasion = "tools.ozone.report.defs#reasonRuleBanEvasion"
	case toolsOzoneReportDefsReasonRuleOther = "tools.ozone.report.defs#reasonRuleOther"
	case toolsOzoneReportDefsReasonSelfHarmContent = "tools.ozone.report.defs#reasonSelfHarmContent"
	case toolsOzoneReportDefsReasonSelfHarmEd = "tools.ozone.report.defs#reasonSelfHarmED"
	case toolsOzoneReportDefsReasonSelfHarmStunts = "tools.ozone.report.defs#reasonSelfHarmStunts"
	case toolsOzoneReportDefsReasonSelfHarmSubstances = "tools.ozone.report.defs#reasonSelfHarmSubstances"
	case toolsOzoneReportDefsReasonSelfHarmOther = "tools.ozone.report.defs#reasonSelfHarmOther"
}


public typealias ToolsOzoneReportDefsReasonViolenceAnimal = String


public typealias ToolsOzoneReportDefsReasonViolenceExtremistContent = String


public typealias ToolsOzoneReportDefsReasonViolenceGlorification = String


public typealias ToolsOzoneReportDefsReasonViolenceGraphicContent = String


public typealias ToolsOzoneReportDefsReasonViolenceOther = String


public typealias ToolsOzoneReportDefsReasonViolenceThreats = String


public typealias ToolsOzoneReportDefsReasonViolenceTrafficking = String


public struct ToolsOzoneReportDefsReopenActivity: Codable, Sendable, Equatable {
	public let previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus?

	public init(
		previousStatus: ToolsOzoneReportDefsAssignmentActivityPreviousStatus? = nil
	) {
		self.previousStatus = previousStatus
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		previousStatus = try container.decodeIfPresent(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .previousStatus)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(previousStatus, forKey: .previousStatus)
	}

	private enum CodingKeys: String, CodingKey {
		case previousStatus = "previousStatus"
	}
}


public struct ToolsOzoneReportDefsReportActivityView: Codable, Sendable, Equatable {
	public let activity: ToolsOzoneReportDefsReportActivityViewActivity
	public let createdAt: ATProtocolDate
	public let createdBy: DID
	public let id: Int
	public let internalNote: String?
	public let isAutomated: Bool
	public let meta: ATProtocolValueContainer?
	public let moderator: ToolsOzoneTeamDefsMember?
	public let publicNote: String?
	public let reportId: Int

	public init(
		activity: ToolsOzoneReportDefsReportActivityViewActivity,
		createdAt: ATProtocolDate,
		createdBy: DID,
		id: Int,
		internalNote: String? = nil,
		isAutomated: Bool,
		meta: ATProtocolValueContainer? = nil,
		moderator: ToolsOzoneTeamDefsMember? = nil,
		publicNote: String? = nil,
		reportId: Int
	) {
		self.activity = activity
		self.createdAt = createdAt
		self.createdBy = createdBy
		self.id = id
		self.internalNote = internalNote
		self.isAutomated = isAutomated
		self.meta = meta
		self.moderator = moderator
		self.publicNote = publicNote
		self.reportId = reportId
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		activity = try container.decode(ToolsOzoneReportDefsReportActivityViewActivity.self, forKey: .activity)
		createdAt = try container.decode(ATProtocolDate.self, forKey: .createdAt)
		createdBy = try container.decode(DID.self, forKey: .createdBy)
		id = try container.decode(Int.self, forKey: .id)
		internalNote = try container.decodeIfPresent(String.self, forKey: .internalNote)
		isAutomated = try container.decode(Bool.self, forKey: .isAutomated)
		meta = try container.decodeIfPresent(ATProtocolValueContainer.self, forKey: .meta)
		moderator = try container.decodeIfPresent(ToolsOzoneTeamDefsMember.self, forKey: .moderator)
		publicNote = try container.decodeIfPresent(String.self, forKey: .publicNote)
		reportId = try container.decode(Int.self, forKey: .reportId)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(activity, forKey: .activity)
		try container.encode(createdAt, forKey: .createdAt)
		try container.encode(createdBy, forKey: .createdBy)
		try container.encode(id, forKey: .id)
		try container.encodeIfPresent(internalNote, forKey: .internalNote)
		try container.encode(isAutomated, forKey: .isAutomated)
		try container.encodeIfPresent(meta, forKey: .meta)
		try container.encodeIfPresent(moderator, forKey: .moderator)
		try container.encodeIfPresent(publicNote, forKey: .publicNote)
		try container.encode(reportId, forKey: .reportId)
	}

	private enum CodingKeys: String, CodingKey {
		case activity = "activity"
		case createdAt = "createdAt"
		case createdBy = "createdBy"
		case id = "id"
		case internalNote = "internalNote"
		case isAutomated = "isAutomated"
		case meta = "meta"
		case moderator = "moderator"
		case publicNote = "publicNote"
		case reportId = "reportId"
	}
}


public indirect enum ToolsOzoneReportDefsReportActivityViewActivity: Codable, Sendable, Equatable {
	case queueActivity(ToolsOzoneReportDefsQueueActivity)
	case assignmentActivity(ToolsOzoneReportDefsAssignmentActivity)
	case escalationActivity(ToolsOzoneReportDefsEscalationActivity)
	case closeActivity(ToolsOzoneReportDefsCloseActivity)
	case reopenActivity(ToolsOzoneReportDefsReopenActivity)
	case noteActivity(ToolsOzoneReportDefsNoteActivity)
	case unexpected(ATProtocolValueContainer)

	public init(from decoder: Decoder) throws {
		let typeIdentifier = try ATProtocolDecoder.decodeTypeIdentifier(from: decoder)
		switch typeIdentifier {
		case "tools.ozone.report.defs#queueActivity": self = .queueActivity(try ToolsOzoneReportDefsQueueActivity(from: decoder))
		case "tools.ozone.report.defs#assignmentActivity": self = .assignmentActivity(try ToolsOzoneReportDefsAssignmentActivity(from: decoder))
		case "tools.ozone.report.defs#escalationActivity": self = .escalationActivity(try ToolsOzoneReportDefsEscalationActivity(from: decoder))
		case "tools.ozone.report.defs#closeActivity": self = .closeActivity(try ToolsOzoneReportDefsCloseActivity(from: decoder))
		case "tools.ozone.report.defs#reopenActivity": self = .reopenActivity(try ToolsOzoneReportDefsReopenActivity(from: decoder))
		case "tools.ozone.report.defs#noteActivity": self = .noteActivity(try ToolsOzoneReportDefsNoteActivity(from: decoder))
		default: self = .unexpected(try ATProtocolValueContainer(from: decoder))
		}
	}

	public func encode(to encoder: Encoder) throws {
		switch self {
		case .queueActivity(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "tools.ozone.report.defs#queueActivity", to: encoder)
		case .assignmentActivity(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "tools.ozone.report.defs#assignmentActivity", to: encoder)
		case .escalationActivity(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "tools.ozone.report.defs#escalationActivity", to: encoder)
		case .closeActivity(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "tools.ozone.report.defs#closeActivity", to: encoder)
		case .reopenActivity(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "tools.ozone.report.defs#reopenActivity", to: encoder)
		case .noteActivity(let value): try ATProtocolEncoder.encodeTagged(value, typeIdentifier: "tools.ozone.report.defs#noteActivity", to: encoder)
		case .unexpected(let value): try value.encode(to: encoder)
		}
	}
}


public struct ToolsOzoneReportDefsReportAssignment: Codable, Sendable, Equatable {
	public let assignedAt: ATProtocolDate
	public let did: DID
	public let moderator: ToolsOzoneTeamDefsMember?

	public init(
		assignedAt: ATProtocolDate,
		did: DID,
		moderator: ToolsOzoneTeamDefsMember? = nil
	) {
		self.assignedAt = assignedAt
		self.did = did
		self.moderator = moderator
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		assignedAt = try container.decode(ATProtocolDate.self, forKey: .assignedAt)
		did = try container.decode(DID.self, forKey: .did)
		moderator = try container.decodeIfPresent(ToolsOzoneTeamDefsMember.self, forKey: .moderator)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(assignedAt, forKey: .assignedAt)
		try container.encode(did, forKey: .did)
		try container.encodeIfPresent(moderator, forKey: .moderator)
	}

	private enum CodingKeys: String, CodingKey {
		case assignedAt = "assignedAt"
		case did = "did"
		case moderator = "moderator"
	}
}


public struct ToolsOzoneReportDefsReportView: Codable, Sendable, Equatable {
	public let actionEventIds: [Int]?
	public let actionNote: String?
	public let actions: [ToolsOzoneModerationDefsModEventView]?
	public let assignment: ToolsOzoneReportDefsReportAssignment?
	public let comment: String?
	public let createdAt: ATProtocolDate
	public let eventId: Int
	public let id: Int
	public let isMuted: Bool?
	public let queue: ToolsOzoneQueueDefsQueueView?
	public let queuedAt: ATProtocolDate?
	public let relatedReportCount: Int?
	public let reportType: ComAtprotoModerationDefsReasonType
	public let reportedBy: DID
	public let reporter: ToolsOzoneModerationDefsSubjectView
	public let status: ToolsOzoneReportDefsAssignmentActivityPreviousStatus
	public let subject: ToolsOzoneModerationDefsSubjectView
	public let subjectStatus: ToolsOzoneModerationDefsSubjectStatusView?
	public let updatedAt: ATProtocolDate?

	public init(
		actionEventIds: [Int]? = nil,
		actionNote: String? = nil,
		actions: [ToolsOzoneModerationDefsModEventView]? = nil,
		assignment: ToolsOzoneReportDefsReportAssignment? = nil,
		comment: String? = nil,
		createdAt: ATProtocolDate,
		eventId: Int,
		id: Int,
		isMuted: Bool? = nil,
		queue: ToolsOzoneQueueDefsQueueView? = nil,
		queuedAt: ATProtocolDate? = nil,
		relatedReportCount: Int? = nil,
		reportType: ComAtprotoModerationDefsReasonType,
		reportedBy: DID,
		reporter: ToolsOzoneModerationDefsSubjectView,
		status: ToolsOzoneReportDefsAssignmentActivityPreviousStatus,
		subject: ToolsOzoneModerationDefsSubjectView,
		subjectStatus: ToolsOzoneModerationDefsSubjectStatusView? = nil,
		updatedAt: ATProtocolDate? = nil
	) {
		self.actionEventIds = actionEventIds
		self.actionNote = actionNote
		self.actions = actions
		self.assignment = assignment
		self.comment = comment
		self.createdAt = createdAt
		self.eventId = eventId
		self.id = id
		self.isMuted = isMuted
		self.queue = queue
		self.queuedAt = queuedAt
		self.relatedReportCount = relatedReportCount
		self.reportType = reportType
		self.reportedBy = reportedBy
		self.reporter = reporter
		self.status = status
		self.subject = subject
		self.subjectStatus = subjectStatus
		self.updatedAt = updatedAt
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		actionEventIds = try container.decodeIfPresent([Int].self, forKey: .actionEventIds)
		actionNote = try container.decodeIfPresent(String.self, forKey: .actionNote)
		actions = try container.decodeIfPresent([ToolsOzoneModerationDefsModEventView].self, forKey: .actions)
		assignment = try container.decodeIfPresent(ToolsOzoneReportDefsReportAssignment.self, forKey: .assignment)
		comment = try container.decodeIfPresent(String.self, forKey: .comment)
		createdAt = try container.decode(ATProtocolDate.self, forKey: .createdAt)
		eventId = try container.decode(Int.self, forKey: .eventId)
		id = try container.decode(Int.self, forKey: .id)
		isMuted = try container.decodeIfPresent(Bool.self, forKey: .isMuted)
		queue = try container.decodeIfPresent(ToolsOzoneQueueDefsQueueView.self, forKey: .queue)
		queuedAt = try container.decodeIfPresent(ATProtocolDate.self, forKey: .queuedAt)
		relatedReportCount = try container.decodeIfPresent(Int.self, forKey: .relatedReportCount)
		reportType = try container.decode(ComAtprotoModerationDefsReasonType.self, forKey: .reportType)
		reportedBy = try container.decode(DID.self, forKey: .reportedBy)
		reporter = try container.decode(ToolsOzoneModerationDefsSubjectView.self, forKey: .reporter)
		status = try container.decode(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .status)
		subject = try container.decode(ToolsOzoneModerationDefsSubjectView.self, forKey: .subject)
		subjectStatus = try container.decodeIfPresent(ToolsOzoneModerationDefsSubjectStatusView.self, forKey: .subjectStatus)
		updatedAt = try container.decodeIfPresent(ATProtocolDate.self, forKey: .updatedAt)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(actionEventIds, forKey: .actionEventIds)
		try container.encodeIfPresent(actionNote, forKey: .actionNote)
		try container.encodeIfPresent(actions, forKey: .actions)
		try container.encodeIfPresent(assignment, forKey: .assignment)
		try container.encodeIfPresent(comment, forKey: .comment)
		try container.encode(createdAt, forKey: .createdAt)
		try container.encode(eventId, forKey: .eventId)
		try container.encode(id, forKey: .id)
		try container.encodeIfPresent(isMuted, forKey: .isMuted)
		try container.encodeIfPresent(queue, forKey: .queue)
		try container.encodeIfPresent(queuedAt, forKey: .queuedAt)
		try container.encodeIfPresent(relatedReportCount, forKey: .relatedReportCount)
		try container.encode(reportType, forKey: .reportType)
		try container.encode(reportedBy, forKey: .reportedBy)
		try container.encode(reporter, forKey: .reporter)
		try container.encode(status, forKey: .status)
		try container.encode(subject, forKey: .subject)
		try container.encodeIfPresent(subjectStatus, forKey: .subjectStatus)
		try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
	}

	private enum CodingKeys: String, CodingKey {
		case actionEventIds = "actionEventIds"
		case actionNote = "actionNote"
		case actions = "actions"
		case assignment = "assignment"
		case comment = "comment"
		case createdAt = "createdAt"
		case eventId = "eventId"
		case id = "id"
		case isMuted = "isMuted"
		case queue = "queue"
		case queuedAt = "queuedAt"
		case relatedReportCount = "relatedReportCount"
		case reportType = "reportType"
		case reportedBy = "reportedBy"
		case reporter = "reporter"
		case status = "status"
		case subject = "subject"
		case subjectStatus = "subjectStatus"
		case updatedAt = "updatedAt"
	}
}


public struct ToolsOzoneReportGetAssignmentsOutput: Codable, Sendable, Equatable {
	public let assignments: [ToolsOzoneReportDefsAssignmentView]
	public let cursor: String?

	public init(
		assignments: [ToolsOzoneReportDefsAssignmentView],
		cursor: String? = nil
	) {
		self.assignments = assignments
		self.cursor = cursor
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		assignments = try container.decode([ToolsOzoneReportDefsAssignmentView].self, forKey: .assignments)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(assignments, forKey: .assignments)
		try container.encodeIfPresent(cursor, forKey: .cursor)
	}

	private enum CodingKeys: String, CodingKey {
		case assignments = "assignments"
		case cursor = "cursor"
	}
}


public struct ToolsOzoneReportGetAssignmentsParameters: Codable, Sendable, Equatable {
	public let cursor: String?
	public let dids: [DID]?
	public let limit: Int?
	public let onlyActive: Bool?
	public let reportIds: [Int]?

	public init(
		cursor: String? = nil,
		dids: [DID]? = nil,
		limit: Int? = nil,
		onlyActive: Bool? = nil,
		reportIds: [Int]? = nil
	) {
		self.cursor = cursor
		self.dids = dids
		self.limit = limit
		self.onlyActive = onlyActive
		self.reportIds = reportIds
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
		dids = try container.decodeIfPresent([DID].self, forKey: .dids)
		limit = try container.decodeIfPresent(Int.self, forKey: .limit)
		onlyActive = try container.decodeIfPresent(Bool.self, forKey: .onlyActive)
		reportIds = try container.decodeIfPresent([Int].self, forKey: .reportIds)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(cursor, forKey: .cursor)
		try container.encodeIfPresent(dids, forKey: .dids)
		try container.encodeIfPresent(limit, forKey: .limit)
		try container.encodeIfPresent(onlyActive, forKey: .onlyActive)
		try container.encodeIfPresent(reportIds, forKey: .reportIds)
	}

	public func asQueryItems() -> [URLQueryItem] {
		var items: [URLQueryItem] = []
		if let value = cursor {
			value.appendQueryItems(named: "cursor", to: &items)
		}
		if let value = dids {
			value.appendQueryItems(named: "dids", to: &items)
		}
		if let value = limit {
			value.appendQueryItems(named: "limit", to: &items)
		}
		if let value = onlyActive {
			value.appendQueryItems(named: "onlyActive", to: &items)
		}
		if let value = reportIds {
			value.appendQueryItems(named: "reportIds", to: &items)
		}
		return items
	}

	private enum CodingKeys: String, CodingKey {
		case cursor = "cursor"
		case dids = "dids"
		case limit = "limit"
		case onlyActive = "onlyActive"
		case reportIds = "reportIds"
	}
}


public struct ToolsOzoneReportGetHistoricalStatsOutput: Codable, Sendable, Equatable {
	public let cursor: String?
	public let stats: [ToolsOzoneReportDefsHistoricalStats]

	public init(
		cursor: String? = nil,
		stats: [ToolsOzoneReportDefsHistoricalStats]
	) {
		self.cursor = cursor
		self.stats = stats
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
		stats = try container.decode([ToolsOzoneReportDefsHistoricalStats].self, forKey: .stats)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(cursor, forKey: .cursor)
		try container.encode(stats, forKey: .stats)
	}

	private enum CodingKeys: String, CodingKey {
		case cursor = "cursor"
		case stats = "stats"
	}
}


public struct ToolsOzoneReportGetHistoricalStatsParameters: Codable, Sendable, Equatable {
	public let cursor: String?
	public let endDate: ATProtocolDate?
	public let limit: Int?
	public let moderatorDid: DID?
	public let queueId: Int?
	public let reportTypes: [String]?
	public let startDate: ATProtocolDate?

	public init(
		cursor: String? = nil,
		endDate: ATProtocolDate? = nil,
		limit: Int? = nil,
		moderatorDid: DID? = nil,
		queueId: Int? = nil,
		reportTypes: [String]? = nil,
		startDate: ATProtocolDate? = nil
	) {
		self.cursor = cursor
		self.endDate = endDate
		self.limit = limit
		self.moderatorDid = moderatorDid
		self.queueId = queueId
		self.reportTypes = reportTypes
		self.startDate = startDate
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
		endDate = try container.decodeIfPresent(ATProtocolDate.self, forKey: .endDate)
		limit = try container.decodeIfPresent(Int.self, forKey: .limit)
		moderatorDid = try container.decodeIfPresent(DID.self, forKey: .moderatorDid)
		queueId = try container.decodeIfPresent(Int.self, forKey: .queueId)
		reportTypes = try container.decodeIfPresent([String].self, forKey: .reportTypes)
		startDate = try container.decodeIfPresent(ATProtocolDate.self, forKey: .startDate)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(cursor, forKey: .cursor)
		try container.encodeIfPresent(endDate, forKey: .endDate)
		try container.encodeIfPresent(limit, forKey: .limit)
		try container.encodeIfPresent(moderatorDid, forKey: .moderatorDid)
		try container.encodeIfPresent(queueId, forKey: .queueId)
		try container.encodeIfPresent(reportTypes, forKey: .reportTypes)
		try container.encodeIfPresent(startDate, forKey: .startDate)
	}

	public func asQueryItems() -> [URLQueryItem] {
		var items: [URLQueryItem] = []
		if let value = cursor {
			value.appendQueryItems(named: "cursor", to: &items)
		}
		if let value = endDate {
			value.appendQueryItems(named: "endDate", to: &items)
		}
		if let value = limit {
			value.appendQueryItems(named: "limit", to: &items)
		}
		if let value = moderatorDid {
			value.appendQueryItems(named: "moderatorDid", to: &items)
		}
		if let value = queueId {
			value.appendQueryItems(named: "queueId", to: &items)
		}
		if let value = reportTypes {
			value.appendQueryItems(named: "reportTypes", to: &items)
		}
		if let value = startDate {
			value.appendQueryItems(named: "startDate", to: &items)
		}
		return items
	}

	private enum CodingKeys: String, CodingKey {
		case cursor = "cursor"
		case endDate = "endDate"
		case limit = "limit"
		case moderatorDid = "moderatorDid"
		case queueId = "queueId"
		case reportTypes = "reportTypes"
		case startDate = "startDate"
	}
}


public enum ToolsOzoneReportGetLatestReportError: String, Swift.Error, CaseIterable, Sendable {
	case notFound = "NotFound"

	public init?(transportError: XRPCTransportError) {
		guard let rawValue = transportError.payload?.error else {
			return nil
		}
		self.init(rawValue: rawValue)
	}
}


public struct ToolsOzoneReportGetLatestReportOutput: Codable, Sendable, Equatable {
	public let report: ToolsOzoneReportDefsReportView

	public init(
		report: ToolsOzoneReportDefsReportView
	) {
		self.report = report
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		report = try container.decode(ToolsOzoneReportDefsReportView.self, forKey: .report)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(report, forKey: .report)
	}

	private enum CodingKeys: String, CodingKey {
		case report = "report"
	}
}


public struct ToolsOzoneReportGetLatestReportParameters: Codable, Sendable, Equatable {

	public init() {}

	public init(from decoder: Decoder) throws {
		_ = try decoder.container(keyedBy: CodingKeys.self)
	}

	public func encode(to encoder: Encoder) throws {
		_ = encoder.container(keyedBy: CodingKeys.self)
	}

	public func asQueryItems() -> [URLQueryItem] {
		[]
	}

	private struct CodingKeys: CodingKey {
		let stringValue = ""
		init?(stringValue: String) {
			return nil
		}

		let intValue: Int? = nil
		init?(intValue: Int) {
			return nil
		}
	}
}


public struct ToolsOzoneReportGetLiveStatsOutput: Codable, Sendable, Equatable {
	public let stats: ToolsOzoneReportDefsLiveStats

	public init(
		stats: ToolsOzoneReportDefsLiveStats
	) {
		self.stats = stats
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		stats = try container.decode(ToolsOzoneReportDefsLiveStats.self, forKey: .stats)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(stats, forKey: .stats)
	}

	private enum CodingKeys: String, CodingKey {
		case stats = "stats"
	}
}


public struct ToolsOzoneReportGetLiveStatsParameters: Codable, Sendable, Equatable {
	public let moderatorDid: DID?
	public let queueId: Int?
	public let reportTypes: [String]?

	public init(
		moderatorDid: DID? = nil,
		queueId: Int? = nil,
		reportTypes: [String]? = nil
	) {
		self.moderatorDid = moderatorDid
		self.queueId = queueId
		self.reportTypes = reportTypes
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		moderatorDid = try container.decodeIfPresent(DID.self, forKey: .moderatorDid)
		queueId = try container.decodeIfPresent(Int.self, forKey: .queueId)
		reportTypes = try container.decodeIfPresent([String].self, forKey: .reportTypes)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(moderatorDid, forKey: .moderatorDid)
		try container.encodeIfPresent(queueId, forKey: .queueId)
		try container.encodeIfPresent(reportTypes, forKey: .reportTypes)
	}

	public func asQueryItems() -> [URLQueryItem] {
		var items: [URLQueryItem] = []
		if let value = moderatorDid {
			value.appendQueryItems(named: "moderatorDid", to: &items)
		}
		if let value = queueId {
			value.appendQueryItems(named: "queueId", to: &items)
		}
		if let value = reportTypes {
			value.appendQueryItems(named: "reportTypes", to: &items)
		}
		return items
	}

	private enum CodingKeys: String, CodingKey {
		case moderatorDid = "moderatorDid"
		case queueId = "queueId"
		case reportTypes = "reportTypes"
	}
}


public enum ToolsOzoneReportGetReportError: String, Swift.Error, CaseIterable, Sendable {
	case notFound = "NotFound"

	public init?(transportError: XRPCTransportError) {
		guard let rawValue = transportError.payload?.error else {
			return nil
		}
		self.init(rawValue: rawValue)
	}
}


public typealias ToolsOzoneReportGetReportOutput = ToolsOzoneReportDefsReportView


public struct ToolsOzoneReportGetReportParameters: Codable, Sendable, Equatable {
	public let id: Int

	public init(
		id: Int
	) {
		self.id = id
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		id = try container.decode(Int.self, forKey: .id)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(id, forKey: .id)
	}

	public func asQueryItems() -> [URLQueryItem] {
		var items: [URLQueryItem] = []
		id.appendQueryItems(named: "id", to: &items)
		return items
	}

	private enum CodingKeys: String, CodingKey {
		case id = "id"
	}
}


public struct ToolsOzoneReportListActivitiesOutput: Codable, Sendable, Equatable {
	public let activities: [ToolsOzoneReportDefsReportActivityView]
	public let cursor: String?

	public init(
		activities: [ToolsOzoneReportDefsReportActivityView],
		cursor: String? = nil
	) {
		self.activities = activities
		self.cursor = cursor
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		activities = try container.decode([ToolsOzoneReportDefsReportActivityView].self, forKey: .activities)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(activities, forKey: .activities)
		try container.encodeIfPresent(cursor, forKey: .cursor)
	}

	private enum CodingKeys: String, CodingKey {
		case activities = "activities"
		case cursor = "cursor"
	}
}


public struct ToolsOzoneReportListActivitiesParameters: Codable, Sendable, Equatable {
	public let cursor: String?
	public let limit: Int?
	public let reportId: Int

	public init(
		cursor: String? = nil,
		limit: Int? = nil,
		reportId: Int
	) {
		self.cursor = cursor
		self.limit = limit
		self.reportId = reportId
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
		limit = try container.decodeIfPresent(Int.self, forKey: .limit)
		reportId = try container.decode(Int.self, forKey: .reportId)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(cursor, forKey: .cursor)
		try container.encodeIfPresent(limit, forKey: .limit)
		try container.encode(reportId, forKey: .reportId)
	}

	public func asQueryItems() -> [URLQueryItem] {
		var items: [URLQueryItem] = []
		if let value = cursor {
			value.appendQueryItems(named: "cursor", to: &items)
		}
		if let value = limit {
			value.appendQueryItems(named: "limit", to: &items)
		}
		reportId.appendQueryItems(named: "reportId", to: &items)
		return items
	}

	private enum CodingKeys: String, CodingKey {
		case cursor = "cursor"
		case limit = "limit"
		case reportId = "reportId"
	}
}


public struct ToolsOzoneReportQueryReportsOutput: Codable, Sendable, Equatable {
	public let cursor: String?
	public let reports: [ToolsOzoneReportDefsReportView]

	public init(
		cursor: String? = nil,
		reports: [ToolsOzoneReportDefsReportView]
	) {
		self.cursor = cursor
		self.reports = reports
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
		reports = try container.decode([ToolsOzoneReportDefsReportView].self, forKey: .reports)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(cursor, forKey: .cursor)
		try container.encode(reports, forKey: .reports)
	}

	private enum CodingKeys: String, CodingKey {
		case cursor = "cursor"
		case reports = "reports"
	}
}


public struct ToolsOzoneReportQueryReportsParameters: Codable, Sendable, Equatable {
	public let assignedTo: DID?
	public let collections: [NSID]?
	public let cursor: String?
	public let did: DID?
	public let isMuted: Bool?
	public let limit: Int?
	public let queueId: Int?
	public let reportTypes: [String]?
	public let reportedAfter: ATProtocolDate?
	public let reportedBefore: ATProtocolDate?
	public let sortDirection: String?
	public let sortField: String?
	public let status: ToolsOzoneReportDefsAssignmentActivityPreviousStatus
	public let subject: String?
	public let subjectType: ToolsOzoneReportQueryReportsParametersSubjectType?

	public init(
		assignedTo: DID? = nil,
		collections: [NSID]? = nil,
		cursor: String? = nil,
		did: DID? = nil,
		isMuted: Bool? = nil,
		limit: Int? = nil,
		queueId: Int? = nil,
		reportTypes: [String]? = nil,
		reportedAfter: ATProtocolDate? = nil,
		reportedBefore: ATProtocolDate? = nil,
		sortDirection: String? = nil,
		sortField: String? = nil,
		status: ToolsOzoneReportDefsAssignmentActivityPreviousStatus,
		subject: String? = nil,
		subjectType: ToolsOzoneReportQueryReportsParametersSubjectType? = nil
	) {
		self.assignedTo = assignedTo
		self.collections = collections
		self.cursor = cursor
		self.did = did
		self.isMuted = isMuted
		self.limit = limit
		self.queueId = queueId
		self.reportTypes = reportTypes
		self.reportedAfter = reportedAfter
		self.reportedBefore = reportedBefore
		self.sortDirection = sortDirection
		self.sortField = sortField
		self.status = status
		self.subject = subject
		self.subjectType = subjectType
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		assignedTo = try container.decodeIfPresent(DID.self, forKey: .assignedTo)
		collections = try container.decodeIfPresent([NSID].self, forKey: .collections)
		cursor = try container.decodeIfPresent(String.self, forKey: .cursor)
		did = try container.decodeIfPresent(DID.self, forKey: .did)
		isMuted = try container.decodeIfPresent(Bool.self, forKey: .isMuted)
		limit = try container.decodeIfPresent(Int.self, forKey: .limit)
		queueId = try container.decodeIfPresent(Int.self, forKey: .queueId)
		reportTypes = try container.decodeIfPresent([String].self, forKey: .reportTypes)
		reportedAfter = try container.decodeIfPresent(ATProtocolDate.self, forKey: .reportedAfter)
		reportedBefore = try container.decodeIfPresent(ATProtocolDate.self, forKey: .reportedBefore)
		sortDirection = try container.decodeIfPresent(String.self, forKey: .sortDirection)
		sortField = try container.decodeIfPresent(String.self, forKey: .sortField)
		status = try container.decode(ToolsOzoneReportDefsAssignmentActivityPreviousStatus.self, forKey: .status)
		subject = try container.decodeIfPresent(String.self, forKey: .subject)
		subjectType = try container.decodeIfPresent(ToolsOzoneReportQueryReportsParametersSubjectType.self, forKey: .subjectType)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(assignedTo, forKey: .assignedTo)
		try container.encodeIfPresent(collections, forKey: .collections)
		try container.encodeIfPresent(cursor, forKey: .cursor)
		try container.encodeIfPresent(did, forKey: .did)
		try container.encodeIfPresent(isMuted, forKey: .isMuted)
		try container.encodeIfPresent(limit, forKey: .limit)
		try container.encodeIfPresent(queueId, forKey: .queueId)
		try container.encodeIfPresent(reportTypes, forKey: .reportTypes)
		try container.encodeIfPresent(reportedAfter, forKey: .reportedAfter)
		try container.encodeIfPresent(reportedBefore, forKey: .reportedBefore)
		try container.encodeIfPresent(sortDirection, forKey: .sortDirection)
		try container.encodeIfPresent(sortField, forKey: .sortField)
		try container.encode(status, forKey: .status)
		try container.encodeIfPresent(subject, forKey: .subject)
		try container.encodeIfPresent(subjectType, forKey: .subjectType)
	}

	public func asQueryItems() -> [URLQueryItem] {
		var items: [URLQueryItem] = []
		if let value = assignedTo {
			value.appendQueryItems(named: "assignedTo", to: &items)
		}
		if let value = collections {
			value.appendQueryItems(named: "collections", to: &items)
		}
		if let value = cursor {
			value.appendQueryItems(named: "cursor", to: &items)
		}
		if let value = did {
			value.appendQueryItems(named: "did", to: &items)
		}
		if let value = isMuted {
			value.appendQueryItems(named: "isMuted", to: &items)
		}
		if let value = limit {
			value.appendQueryItems(named: "limit", to: &items)
		}
		if let value = queueId {
			value.appendQueryItems(named: "queueId", to: &items)
		}
		if let value = reportTypes {
			value.appendQueryItems(named: "reportTypes", to: &items)
		}
		if let value = reportedAfter {
			value.appendQueryItems(named: "reportedAfter", to: &items)
		}
		if let value = reportedBefore {
			value.appendQueryItems(named: "reportedBefore", to: &items)
		}
		if let value = sortDirection {
			value.appendQueryItems(named: "sortDirection", to: &items)
		}
		if let value = sortField {
			value.appendQueryItems(named: "sortField", to: &items)
		}
		status.appendQueryItems(named: "status", to: &items)
		if let value = subject {
			value.appendQueryItems(named: "subject", to: &items)
		}
		if let value = subjectType {
			value.appendQueryItems(named: "subjectType", to: &items)
		}
		return items
	}

	private enum CodingKeys: String, CodingKey {
		case assignedTo = "assignedTo"
		case collections = "collections"
		case cursor = "cursor"
		case did = "did"
		case isMuted = "isMuted"
		case limit = "limit"
		case queueId = "queueId"
		case reportTypes = "reportTypes"
		case reportedAfter = "reportedAfter"
		case reportedBefore = "reportedBefore"
		case sortDirection = "sortDirection"
		case sortField = "sortField"
		case status = "status"
		case subject = "subject"
		case subjectType = "subjectType"
	}
}


public enum ToolsOzoneReportQueryReportsParametersSubjectType: String, Codable, CaseIterable, QueryParameterValue, Sendable {
	case account = "account"
	case record = "record"
}


public enum ToolsOzoneReportReassignQueueError: String, Swift.Error, CaseIterable, Sendable {
	case alreadyInTargetQueue = "AlreadyInTargetQueue"
	case queueDisabled = "QueueDisabled"
	case queueNotFound = "QueueNotFound"
	case reportClosed = "ReportClosed"
	case reportNotFound = "ReportNotFound"

	public init?(transportError: XRPCTransportError) {
		guard let rawValue = transportError.payload?.error else {
			return nil
		}
		self.init(rawValue: rawValue)
	}
}


public struct ToolsOzoneReportReassignQueueInput: Codable, Sendable, Equatable {
	public let comment: String?
	public let queueId: Int
	public let reportId: Int

	public init(
		comment: String? = nil,
		queueId: Int,
		reportId: Int
	) {
		self.comment = comment
		self.queueId = queueId
		self.reportId = reportId
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		comment = try container.decodeIfPresent(String.self, forKey: .comment)
		queueId = try container.decode(Int.self, forKey: .queueId)
		reportId = try container.decode(Int.self, forKey: .reportId)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encodeIfPresent(comment, forKey: .comment)
		try container.encode(queueId, forKey: .queueId)
		try container.encode(reportId, forKey: .reportId)
	}

	private enum CodingKeys: String, CodingKey {
		case comment = "comment"
		case queueId = "queueId"
		case reportId = "reportId"
	}
}


public struct ToolsOzoneReportReassignQueueOutput: Codable, Sendable, Equatable {
	public let report: ToolsOzoneReportDefsReportView

	public init(
		report: ToolsOzoneReportDefsReportView
	) {
		self.report = report
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		report = try container.decode(ToolsOzoneReportDefsReportView.self, forKey: .report)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(report, forKey: .report)
	}

	private enum CodingKeys: String, CodingKey {
		case report = "report"
	}
}


public struct ToolsOzoneReportRefreshStatsInput: Codable, Sendable, Equatable {
	public let endDate: String
	public let queueIds: [Int]?
	public let startDate: String

	public init(
		endDate: String,
		queueIds: [Int]? = nil,
		startDate: String
	) {
		self.endDate = endDate
		self.queueIds = queueIds
		self.startDate = startDate
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		endDate = try container.decode(String.self, forKey: .endDate)
		queueIds = try container.decodeIfPresent([Int].self, forKey: .queueIds)
		startDate = try container.decode(String.self, forKey: .startDate)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(endDate, forKey: .endDate)
		try container.encodeIfPresent(queueIds, forKey: .queueIds)
		try container.encode(startDate, forKey: .startDate)
	}

	private enum CodingKeys: String, CodingKey {
		case endDate = "endDate"
		case queueIds = "queueIds"
		case startDate = "startDate"
	}
}


public struct ToolsOzoneReportRefreshStatsOutput: Codable, Sendable, Equatable {

	public init() {}

	public init(from decoder: Decoder) throws {
		_ = try decoder.container(keyedBy: CodingKeys.self)
	}

	public func encode(to encoder: Encoder) throws {
		_ = encoder.container(keyedBy: CodingKeys.self)
	}

	private struct CodingKeys: CodingKey {
		let stringValue = ""
		init?(stringValue: String) {
			return nil
		}

		let intValue: Int? = nil
		init?(intValue: Int) {
			return nil
		}
	}
}


public enum ToolsOzoneReportUnassignModeratorError: String, Swift.Error, CaseIterable, Sendable {
	case invalidAssignment = "InvalidAssignment"

	public init?(transportError: XRPCTransportError) {
		guard let rawValue = transportError.payload?.error else {
			return nil
		}
		self.init(rawValue: rawValue)
	}
}


public struct ToolsOzoneReportUnassignModeratorInput: Codable, Sendable, Equatable {
	public let reportId: Int

	public init(
		reportId: Int
	) {
		self.reportId = reportId
	}

	public init(from decoder: Decoder) throws {
		let container = try decoder.container(keyedBy: CodingKeys.self)
		reportId = try container.decode(Int.self, forKey: .reportId)
	}

	public func encode(to encoder: Encoder) throws {
		var container = encoder.container(keyedBy: CodingKeys.self)
		try container.encode(reportId, forKey: .reportId)
	}

	private enum CodingKeys: String, CodingKey {
		case reportId = "reportId"
	}
}


public typealias ToolsOzoneReportUnassignModeratorOutput = ToolsOzoneReportDefsAssignmentView


